
# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = [
    'exec-and-forget /run/current-system/sw/bin/sketchybar',
    'exec-and-forget borders active_color=0xFFfab387 inactive_color=0x00000000 width=5.0'

]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    '/run/current-system/sw/bin/sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 6
inner.vertical =   6
outer.left =       6
outer.bottom =     6
outer.top =   [{ monitor."built-in" = 12 }, 44]
outer.right =      6

[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:$${PATH}'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
alt-enter = 'exec-and-forget open -a kitty'

alt-w = 'exec-and-forget open -a firefox'

alt-b = 'exec-and-forget open -a finder'

alt-t = 'exec-and-forget open -a telegram'
alt-s = 'exec-and-forget open -a signal'
alt-v = 'exec-and-forget open -a viber'

alt-c = '''exec-and-forget open -a "Visual Studio Code"'''

alt-o = 'exec-and-forget open -a OrcaSlicer'

alt-z = 'exec-and-forget open -a zed'

alt-p = 'exec-and-forget open -a Bitwarden'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'   # Terminal
alt-3 = 'workspace 3'   
alt-4 = 'workspace 4'   
alt-5 = 'workspace 5'   # Orca
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'   # Browser
alt-8 = 'workspace 8'   # IDE 
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'  # Chat


# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'


# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-e = 'balance-sizes' # Balance sizes of all windows in the current workspace
alt-f = 'layout floating tiling' # Toggle between floating and tiling layout
alt-m = 'fullscreen'
alt-shift-r = 'reload-config'

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

alt-r = 'mode resize'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# Declare 'resize' binding mode
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['mode main']


# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']


# Window to workspace bindings

## Notes

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = 'move-node-to-workspace 1' 

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 1' 

## Terminals

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 2' 

[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = 'move-node-to-workspace 2' 

## Orca

[[on-window-detected]]
if.app-id = 'com.softfever3d.orca-slicer'
run = 'move-node-to-workspace 5' 

## Browsers

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 7' 

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 7' 

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 7' 

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace 7' 

[[on-window-detected]]
if.app-id = 'org.torproject.torbrowser'
run = 'move-node-to-workspace 7' 

## IDE

[[on-window-detected]]
if.app-id = 'com.google.android.studio'
run = 'move-node-to-workspace 8' 

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij.ce'
run = 'move-node-to-workspace 8' 

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 8' 

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 8' 

## Chats

[[on-window-detected]]
if.app-id = 'com.viber.osx'
run = 'move-node-to-workspace 10' 

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = 'move-node-to-workspace 10' 

[[on-window-detected]]
if.app-id = 'com.tdesktop.Telegram'
run = 'move-node-to-workspace 10' 

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 10' 


# Force float

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = 'layout floating'


# Workspaces to Display bindings

[workspace-to-monitor-force-assignment]
1 = '^built-in retina display$'   
2 = '^built-in retina display$'   
3 = '^built-in retina display$'     
4 = '^built-in retina display$'    
5 = '^built-in retina display$'  
6 = '^lg hdr wqhd$' 
7 = '^lg hdr wqhd$' 
8 = '^lg hdr wqhd$' 
9 = '^lg hdr wqhd$' 
10 = '^lg hdr wqhd$' 